services:
  - type: web
    name: attendance-bot
    runtime: node
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: BOT_TOKEN
        value: $BOT_TOKEN
        sync: false
    disk:
      name: attendance-data
      mountPath: /usr/src/app/data
      sizeGB: 1